version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    network_mode: host

  app:
    build: .
    command: /bin/sh -c "/node_modules/.bin/ts-node-dev -P /app/microservices/orders/tsconfig.json --no-notify --all-deps /app/microservices/orders/server.ts"
    network_mode: host

